container:
  dockerfile: Dockerfile

task:
  debug_script:
    - pwd
    - ls -la
  build_script:
    - cd verilog
    - find . -name "*.v" -o -name "*.vh" > ../sources.txt
    - cd ../tb
    - for f in *.v; do iverilog -I $(dirname "../verilog/$f") -o "../bin/$(basename $f .v)" "$f" $(cat ../sources.txt); done
  test_script:
    - cd ../bin
    - for f in *; do vvp "$f"; done
