container:
  dockerfile: Dockerfile

task:
  debug_script:
    - pwd
    - ls -la
  build_script:
    - cd verilog
    - for f in ../tb/*.v; do iverilog -I . -o "../bin/$(basename $f .v)" "$f" $(find . -name "*.v" -o -name "*.vh"); done
  test_script:
    - cd ../bin
    - for f in *; do vvp "$f"; done
