container:
  dockerfile: Dockerfile

task:
  debug_script:
    - pwd
    - ls -la
  build_script:
    - find verilog -name "*.v" > sources.txt
    - cd tb
    - for f in *.v; do iverilog -o "../bin/$(basename $f .v)" "$f" $(cat ../sources.txt); done
  test_script:
    - cd ../bin
    - for f in *; do vvp "$f"; done