container:
  dockerfile: Dockerfile

task:
  debug_script:
    - pwd
    - ls -la
  build_script:
    - cd tb
    - for f in *.v; do iverilog -I /tmp/cirrus-ci-build/verilog -o "../bin/$(basename $f .v)" "$f" $(find ../verilog -name "*.v"); done
  test_script:
    - cd ../bin
    - for f in *; do vvp "$f"; done
