language: verilog

services:
  - docker

before_install:
  - docker build -t icarus-verilog_rv32i .

jobs:
  include:
  - stage: Unit Tests
  name: "ALU Tests"
  script: docker run icarus-verilog_rv32i /bin/sh -c "iverilog -grelative-include -o bin/al tb/alu_tb.v ; bin/al| tee /dev/fd/2 | grep -q 'FATAL' && exit 1 || exit 0;"

  - stage: build docker image
    script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t icarus-verilog_rv32i .
    - docker images
    - docker tag icarus-verilog_rv32i $DOCKER_USERNAME/icarus-verilog_rv32i
    - docker push $DOCKER_USERNAME/icarus-verilog_rv32i